;; [[file:config.org::*Generated File Header][Generated File Header:1]]
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; =============================================================
;; DO NOT EDIT THIS FILE DIRECTLY.
;; Generated from ~/.config/doom/config.org
;; Edit that file, tangle with `tangle config`,
;; then reload with M-x doom/reload.
;; =============================================================

;;; Commentary:
;; Doom Emacs user layer.  Covers: Org/Denote/Howm PKM, Consult/Embark
;; navigation, Copilot + Claude Code AI, Treemacs, tab-bar, window management,
;; and Windows-centric defaults for shell paths and emacsclient frames.
;; Targets Windows 11 with the Interception driver (Kanata) and Komorebi WM.

;;; Code:

;; Keep the belt-and-suspenders fix in config.el too — `cd` in
;; early-init.el fixes *scratch*/*Messages*, but `setq-default`
;; here fixes any buffer created later without its own
;; default-directory.
(setq-default default-directory (expand-file-name "~/"))
(cd "~/")
;; Generated File Header:1 ends here

;; [[file:config.org::*Appearance][Appearance:1]]
(setq doom-theme 'catppuccin
      catppuccin-flavor 'mocha
      doom-font (font-spec :family "CaskaydiaMono NFM" :size 18)
      display-line-numbers-type 'relative)
;; Appearance:1 ends here

;; [[file:config.org::*Performance][Performance:1]]
(setq redisplay-skip-fontification-on-input t
      fast-but-imprecise-scrolling t
      read-process-output-max (* 4 1024 1024)
      scroll-margin 4
      scroll-conservatively 101
      scroll-preserve-screen-position t)
;; Performance:1 ends here

;; [[file:config.org::*Shell][Shell:1]]
(let ((bash (executable-find "bash")))
  (when bash
    ;; Doom doctor checks that shell-file-name ends in /bash, /sh, etc.
    ;; On Windows executable-find returns bash.exe; strip .exe to satisfy
    ;; the check while keeping the full .exe path for terminal emulators.
    (setq shell-file-name (replace-regexp-in-string "\\.exe\\'" "" bash))
    (setq-default explicit-shell-file-name bash
                  vterm-shell bash)))
;; Shell:1 ends here

;; [[file:config.org::*Core Settings][Core Settings:1]]
(setq org-directory "~/Documents/org/"
      org-agenda-files (list (expand-file-name "tasks.org"    org-directory)
                             (expand-file-name "notes.org"    org-directory)
                             (expand-file-name "journal.org"  org-directory))

      org-default-notes-file (expand-file-name "journal.org" org-directory)
      org-log-done               'time
      org-startup-indented       t
      org-hide-emphasis-markers  t
      org-pretty-entities        t
      org-todo-keywords
      '((sequence "TODO(t)" "NEXT(n)" "WAIT(w)" "|" "DONE(d)" "CANCELLED(c)")))
(defconst my/org-journal-file
  (expand-file-name "journal.org" org-directory)
  "Canonical journal file used by the datetree workflow.")

;; GTD @context tags — available in all org files.
;; Apply with C-c C-q; filter agenda with / then tag name.
(setq org-tag-alist '(("@computer" . ?c)
                      ("@calls"    . ?p)
                      ("@errands"  . ?e)
                      ("@home"     . ?h)
                      ("@homelab"  . ?l)
                      ("@read"     . ?r)
                      ("@write"    . ?W)))
;; Core Settings:1 ends here

;; [[file:config.org::*Refile][Refile:1]]
(setq org-refile-targets
      `((,(expand-file-name "tasks.org"    org-directory) :maxlevel . 2)
        (,(expand-file-name "notes.org"    org-directory) :maxlevel . 2))
      org-refile-use-outline-path        'file
      org-outline-path-complete-in-steps  nil)
;; Refile:1 ends here

;; [[file:config.org::*Capture Templates][Capture Templates:1]]
(setq org-capture-templates
      `(("j" "Journal log" plain
         (function my/org-journal-capture-log-target)
         "- %U %?"
         :empty-lines 1)
        ("J" "Journal task" plain
         (function my/org-journal-capture-task-target)
         "***** TODO %?"
         :empty-lines 1)))
;; Capture Templates:1 ends here

;; [[file:config.org::*Agenda Views][Agenda Views:1]]
(defun my/org-journal--outline-day-time-at-point ()
  "Return noon on the journal level-3 datetree day containing point, or nil."
  (save-excursion
    (ignore-errors
      (unless (org-at-heading-p)
        (org-back-to-heading t))
      (org-back-to-heading t)
      (while (> (org-outline-level) 3)
        (outline-up-heading 1 t))
      (when (= (org-outline-level) 3)
        (beginning-of-line)
        (when (looking-at "^\\*\\*\\* \\([0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\)")
          (pcase (mapcar #'string-to-number (split-string (match-string 1) "-"))
            (`(,y ,m ,d) (encode-time 12 0 0 d m y)))))))

(defun my/org-journal--today-midnight ()
  "Return encoded time at local midnight for today's calendar date."
  (pcase-let ((`(,sec ,min ,hour ,d ,m ,y . _) (decode-time (current-time))))
    (encode-time 0 0 0 d m y)))

(defun my/org-agenda-skip-journal-past-days ()
  "Skip journal subtrees whose datetree day is before today.
When not in `my/org-journal-file', return nil so other agenda files are unchanged."
  (when (and (derived-mode-p 'org-mode)
             buffer-file-name
             (file-equal-p (expand-file-name buffer-file-name)
                           (expand-file-name my/org-journal-file)))
    (let ((day (my/org-journal--outline-day-time-at-point)))
      (when (and day (time-less-p day (my/org-journal--today-midnight)))
        (save-excursion (org-end-of-subtree t t) (point))))))

(setq org-agenda-skip-function-global #'my/org-agenda-skip-journal-past-days)

(defun my/org-agenda-waiting-on ()
  "Return WAITING_ON property for agenda prefix, or empty string."
  (let ((w (org-entry-get nil "WAITING_ON")))
    (if (and w (not (string-blank-p w)))
        (format "[←%s] " w)
      "")))

(setq org-agenda-custom-commands
      `(("d" "Daily Review"
         ((agenda "" ((org-agenda-span 1)
                      (org-agenda-overriding-header "Today")))
          (todo "NEXT" ((org-agenda-overriding-header "Next Actions")))
          (todo "WAIT" ((org-agenda-overriding-header "Waiting / Follow Up")
                        (org-agenda-prefix-format
                         "  %(my/org-agenda-waiting-on)%-12:c%s")))))
        ("n" "Now (NEXT + TODO)"
         ((todo "NEXT" ((org-agenda-overriding-header "Next")))
          (todo "TODO" ((org-agenda-overriding-header "Unscheduled / inbox-style")))))
        ("w" "Waiting"
         ((todo "WAIT"
                ((org-agenda-overriding-header "Waiting / Follow Up")
                 (org-agenda-prefix-format
                  "  %(my/org-agenda-waiting-on)%-12:c%s")))))
        ("c" . "Context views")
        ("cc" "@computer" ((tags-todo "@computer"
                            ((org-agenda-overriding-header "At computer")))))
        ("cp" "@calls"    ((tags-todo "@calls"
                            ((org-agenda-overriding-header "Calls / phone")))))
        ("ce" "@errands"  ((tags-todo "@errands"
                            ((org-agenda-overriding-header "Errands")))))
        ("ch" "@home"     ((tags-todo "@home"
                            ((org-agenda-overriding-header "At home")))))
        ("cl" "@homelab"  ((tags-todo "@homelab"
                            ((org-agenda-overriding-header "Homelab")))))
        ("cr" "@read"     ((tags-todo "@read"
                            ((org-agenda-overriding-header "Read / Review")))))
        ("cw" "@write"    ((tags-todo "@write"
                            ((org-agenda-overriding-header "Write / Draft")))))
        )))
;; Agenda Views:1 ends here

;; [[file:config.org::*Agenda Views][Agenda Views:2]]
(after! org-agenda
  (add-to-list 'org-agenda-custom-commands
               '("o" "All open tasks from journal"
                 ((todo "TODO"
                        ((org-agenda-files (list my/org-journal-file))
                         (org-agenda-overriding-header "All Open Tasks from Journal")))))
               t))
;; Agenda Views:2 ends here

;; [[file:config.org::*Journal][Journal:1]]
(defun my/org-journal--subtree-end ()
  "Return the end position of the subtree at point."
  (save-excursion
    (org-end-of-subtree t t)
    (point)))

(defun my/org-journal--goto-day-heading (time)
  "Move point to TIME's day heading in the current journal buffer."
  (goto-char (point-min))
  (re-search-forward
   (format "^\\*\\{3\\} %s$"
           (regexp-quote (format-time-string "%Y-%m-%d %A" time)))
   nil t))

(defun my/org-journal--goto-current-day-start ()
  "Move point to the current day's level-3 heading."
  (org-back-to-heading t)
  (while (> (org-outline-level) 3)
    (outline-up-heading 1 t))
  (beginning-of-line))

(defun my/org-journal--goto-heading-in-day (level heading)
  "Move point to HEADING at LEVEL within the current day's subtree."
  (my/org-journal--goto-current-day-start)
  (let ((day-end (my/org-journal--subtree-end)))
    (re-search-forward
     (format "^\\*\\{%d\\} %s$" level (regexp-quote heading))
     day-end t)))

(defun my/org-journal--gregorian-to-time (date)
  "Convert Gregorian DATE to an Emacs time value."
  (pcase-let ((`(,month ,day ,year) date))
    (encode-time 0 0 12 day month year)))

(defun my/org-journal--insert-day-template ()
  "Insert the current day's journal scaffold.
Point must be on the day heading line — moves to end of it so content
inserts after the heading, not before."
  (end-of-line)
  (insert
   (concat
      "\n\n**** Log\n"
      "- " (format-time-string "[%Y-%m-%d %a %H:%M]") " Day opened.\n\n"
      "**** Tasks\n\n"
      "**** EOD\n"
      "***** Done\n- \n\n"
       "***** Next\n- \n")))

(defun my/org-journal--ensure-top-section (heading &optional body)
  "Ensure the current day contains a level-4 HEADING with optional BODY."
  (unless (save-excursion (my/org-journal--goto-heading-in-day 4 heading))
    (my/org-journal--goto-current-day-start)
    (goto-char (my/org-journal--subtree-end))
    (insert (format "\n**** %s\n%s" heading (or body "")))))

(defun my/org-journal--ensure-child-section (parent child &optional body)
  "Ensure PARENT contains a level-5 CHILD heading with optional BODY."
  (when (my/org-journal--goto-heading-in-day 4 parent)
    (let ((parent-end (my/org-journal--subtree-end)))
      (unless (save-excursion
                (goto-char (line-beginning-position))
                (re-search-forward
                 (format "^\\*\\{5\\} %s$" (regexp-quote child))
                 parent-end t))
        (goto-char parent-end)
        (insert (format "\n***** %s\n%s" child (or body "")))))))

(defun my/org-journal--next-heading-point ()
  "Return the buffer position of the next heading after point.
If there is no later heading, return `point-max'."
  (save-excursion
    (forward-line 1)
    (if (re-search-forward "^\\*+ " nil t)
        (match-beginning 0)
      (point-max))))

(defvar-local my/org-journal-structure-ensured nil
  "Buffer-local guard: stores today's date `(month day year)` once the
day scaffold has been ensured for that date.  Nil means no scaffold has
been run yet.  Resets automatically when a new day is opened — compares
against `(calendar-current-date)` in `my/org-journal-ensure-day-structure`.

Checked via `unless` at the top of that function — NOT via
`cl-return-from', which would require an explicit `cl-block' wrapper
in Emacs Lisp.")

(defun my/org-journal-ensure-day-structure ()
  "Ensure today's subtree has the current journal scaffold.
Per-day guard (`my/org-journal-structure-ensured`) limits this to
once per day — safe to call from s, S, yl, yt, etc.

- Sections exist → ensure all present (Log/Tasks/EOD + child Done/Next)
- No sections → insert full template"
  (let ((today (calendar-current-date)))
    (unless (equal my/org-journal-structure-ensured today)
      (setq my/org-journal-structure-ensured today)
      (if (or (save-excursion (my/org-journal--goto-heading-in-day 4 "Log"))
              (save-excursion (my/org-journal--goto-heading-in-day 4 "Tasks"))
              (save-excursion (my/org-journal--goto-heading-in-day 4 "EOD")))
          ;; Has some content — ensure all sections exist
          (progn
            (my/org-journal--ensure-top-section "Log")
            (my/org-journal--ensure-top-section "Tasks")
            (my/org-journal--ensure-top-section "EOD")
            (my/org-journal--ensure-child-section "EOD" "Done")
            (my/org-journal--ensure-child-section "EOD" "Next"))
        ;; Completely fresh day — insert full template and carry forward
        (my/org-journal--insert-day-template)
        (my/org-journal--carry-forward-yesterday)))))

(defun my/org-journal--carry-forward-yesterday ()
  "Copy yesterday's open TODO items to today's Tasks section.
Each carried task gets (YYYY-MM-DD) appended for provenance.
The original stays in yesterday unchanged."
  (let* ((today (calendar-current-date))
         (yesterday (calendar-gregorian-from-absolute
                     (1- (calendar-absolute-from-gregorian today))))
         (yesterday-link (format-time-string "[%Y-%m-%d]"
                          (apply #'encode-time 0 0 0 0
                                 (list (nth 1 yesterday) (nth 0 yesterday) (nth 2 yesterday)))))
         tasks)
    (save-window-excursion
      (find-file my/org-journal-file)
      (org-datetree-find-date-create yesterday)
      (when (my/org-journal--goto-heading-in-day 4 "Tasks")
        (org-back-to-heading t)
        (let ((section-end (save-excursion (org-end-of-subtree t t) (point))))
          (forward-line 1)
          (while (< (point) section-end)
            (when (looking-at "^\\*\\*\\*\\*\\* TODO ")
              (let ((title (buffer-substring-no-properties
                            (match-end 0)
                            (line-end-position))))
                (unless (string-blank-p title)
                  (push title tasks))))
            (forward-line 1)))))
    (when tasks
      (find-file my/org-journal-file)
      (org-datetree-find-date-create today)
      (my/org-journal-ensure-day-structure)
      (my/org-journal--goto-tasks-section)
      (end-of-line)
      (dolist (task (nreverse tasks))
        (insert (concat "\n***** TODO " task " (" yesterday-link ")")))
      (save-buffer)
      (message "Carried forward %d task(s) from %s" (length tasks) yesterday-link))))

(defun my/org-journal--goto-section-end (level heading &optional empty-starter)
  "Go to the end of HEADING at LEVEL within the current day.
If the section is empty and EMPTY-STARTER is non-nil, insert it first.
Always measures the subtree from the section heading so nested headings
(e.g. ***** TODO under **** Tasks) stay inside the correct section."
  (when (my/org-journal--goto-heading-in-day level heading)
    (org-back-to-heading t)
    (let* ((heading-pos (point))
           (section-start (save-excursion (forward-line 1) (point)))
           (section-end (save-excursion
                          (goto-char heading-pos)
                          (org-end-of-subtree t t)
                          (point)))
           (contents (buffer-substring-no-properties section-start section-end)))
      (if (string-blank-p contents)
          (progn
            (goto-char section-start)
            (when (looking-at-p "^\\*+ ")
              (open-line 1))
            (when empty-starter
              (insert empty-starter)))
        (goto-char section-end)
        (skip-chars-backward "\n")
        (end-of-line)))
    (end-of-line)))

(defun my/org-journal-goto-log-section ()
  "Move point to the end of today's Log section."
  (my/org-journal--goto-section-end 4 "Log"))

(defun my/org-journal--goto-tasks-section ()
  "Move point to the end of today's Tasks section."
  (my/org-journal--goto-section-end 4 "Tasks"))

(defun my/org-journal-ensure-log-target ()
  "Ensure today's journal has a usable Log target.
Delegates to `my/org-journal-ensure-day-structure' which handles migration
from old-format days. Then positions point in the Log section."
  (require 'org-datetree)
  (find-file my/org-journal-file)
  (org-datetree-find-date-create (calendar-current-date))
  (my/org-journal-ensure-day-structure)
  (my/org-journal-goto-log-section))

(defun my/org-journal-ensure-tasks-target ()
  "Ensure today's journal has a usable Tasks target.
Delegates to `my/org-journal-ensure-day-structure' which handles migration
from old-format days. Then positions point in the Tasks section."
  (require 'org-datetree)
  (find-file my/org-journal-file)
  (org-datetree-find-date-create (calendar-current-date))
  (my/org-journal-ensure-day-structure)
  (my/org-journal--goto-tasks-section))

(defun my/org-journal-open-section-today (section)
  "Open today's journal and move point to SECTION."
  (interactive)
  (require 'org-datetree)
  (find-file my/org-journal-file)
  (org-datetree-find-date-create (calendar-current-date))
  (my/org-journal-ensure-day-structure)
  (pcase section
    ('plan
     (my/org-journal--goto-tasks-section))
    ('log
     (my/org-journal-goto-log-section))
    ('tasks
     (my/org-journal--goto-tasks-section))
    ('eod
     (my/org-journal--goto-section-end 5 "Done" "- "))
    (_
     (my/org-journal-goto-log-section))))

(defun my/org-open-journal-today ()
  "Open today's journal and land in the Log section."
  (interactive)
  (my/org-journal-open-section-today 'log))

(defalias 'my/org-journal-open-log 'my/org-open-journal-today
  "Open today's journal and land in the Log section.
Alias for `my/org-open-journal-today' — provided for API symmetry
with the other `my/org-journal-open-*' entry points.")

(defun my/org-journal-open-plan ()
  "Open today's journal and land in the Tasks section."
  (interactive)
  (my/org-journal-open-section-today 'plan))

(defun my/org-journal-open-eod ()
  "Open today's journal and land in the EOD section."
  (interactive)
  (my/org-journal-open-section-today 'eod))

(defun my/org-journal-open-tasks ()
  "Open today's journal and land in the Tasks section."
  (interactive)
  (my/org-journal-open-section-today 'tasks))

(defun my/org-journal-capture-log-target ()
  "Open today's journal Log and return point for org-protocol capture.
Uses :insert-here so org-capture inserts at the section end, not at cursor
or the first list in the buffer (see `org-capture-place-item')."
  (set-buffer (find-file-noselect my/org-journal-file))
  (org-with-wide-buffer
    (my/org-journal-ensure-log-target)
    (end-of-line)
    (org-capture-put :insert-here t)
    (point)))

(defun my/org-journal-capture-task-target ()
  "Open today's journal Tasks and return point for org-protocol capture.
Leaves point on the **** Tasks heading so org-capture inserts a ***** TODO
at the bottom of that subtree (same as `my/org-journal-insert-task')."
  (set-buffer (find-file-noselect my/org-journal-file))
  (org-with-wide-buffer
    (my/org-journal-ensure-tasks-target)
    (unless (my/org-journal--goto-heading-in-day 4 "Tasks")
      (user-error "Browser task capture: could not find today's **** Tasks"))
    (org-back-to-heading t)
    (point)))

(defun my/phoneme-insert-transcript (transcript)
  "Insert a Phoneme voice note TRANSCRIPT into today's journal Log.
Called from phoneme-journal.ps1 via emacsclient --eval.
Uses the same org-datetree path as browser captures (yl/yt/ya)."
  (let ((ts (format-time-string "- [%Y-%m-%d %a %H:%M] ")))
    (require 'org-datetree)
    (find-file my/org-journal-file)
    (org-datetree-find-date-create (calendar-current-date))
    (my/org-journal-ensure-day-structure)
    (my/org-journal-goto-log-section)
    (end-of-line)
    (newline)
    (insert ts transcript)
    (save-buffer)
    (message "Phoneme: inserted transcript in journal Log")))

(defun my/phoneme-insert-task (text)
  "Insert a TODO task from TEXT into today's journal Tasks.
Called from TaskCapture Flow Launcher plugin via emacsclient --eval."
  (require 'org-datetree)
  (find-file my/org-journal-file)
  (org-datetree-find-date-create (calendar-current-date))
  (my/org-journal-ensure-day-structure)
  (my/org-journal-ensure-tasks-target)
  (end-of-line)
  (insert (concat "\n***** TODO " text))
  (save-buffer)
  (message "TaskCapture: inserted task in journal Tasks"))

(defun my/flowlauncher-insert-journal-entry (text)
  "Insert TEXT into today's journal Log section.
Called from Quick Journal Flow Launcher plugin via emacsclient --eval."
  (let ((ts (format-time-string "- [%Y-%m-%d %a %H:%M] ")))
    (require 'org-datetree)
    (find-file my/org-journal-file)
    (org-datetree-find-date-create (calendar-current-date))
    (my/org-journal-ensure-day-structure)
    (my/org-journal-goto-log-section)
    (end-of-line)
    (newline)
    (insert ts text)
    (save-buffer)
    (message "Flow Launcher: inserted entry in journal Log")))

(defun my/flowlauncher-insert-journal-task (text)
  "Insert a TODO task from TEXT into today's journal Tasks.
Called from Quick Task Flow Launcher plugin via emacsclient --eval."
  (require 'org-datetree)
  (find-file my/org-journal-file)
  (org-datetree-find-date-create (calendar-current-date))
  (my/org-journal-ensure-day-structure)
  (my/org-journal-ensure-tasks-target)
  (end-of-line)
  (insert (concat "\n***** TODO " text))
  (save-buffer)
  (message "Flow Launcher: inserted task in journal Tasks"))

(defun my/phoneme-insert-denote (transcript)
  "Create a Denote note from a Phoneme voice TRANSCRIPT.
Tags: :voice:journal:. No journal entry — pure Denote capture.
Called from phoneme-denote.ps1 via emacsclient --eval."
  (let* ((title      (concat "Voice note " (format-time-string "%Y-%m-%d %H:%M")))
         (keywords   '("voice"))
         (dir        (my/denote--library-subdirectory keywords))
         (id         (format-time-string "%Y%m%dT%H%M%S"))
         (slug       (denote-sluggify title))
         (kw-combined (denote-keywords-combine
                       (denote-sluggify-keywords-and-apply-rules keywords)))
         (fname      (format "%s/%s--%s__%s.org" dir id slug kw-combined)))
    (make-directory dir t)
    (with-temp-file fname
      (set-buffer-file-coding-system 'utf-8)
      (insert (format "#+title:      %s\n" title))
      (insert (format "#+date:       %s\n" (format-time-string "[%Y-%m-%d %a]")))
      (insert "#+filetags:   :voice:\n")
      (insert (format "#+identifier: %s\n\n" id))
      (insert "* Transcript\n\n")
      (insert transcript "\n"))
    (message "Denote: saved voice note")))

(defun my/org-journal--strip-plan-line-text (s)
  "Strip checkbox or heading markers from S for use as a heading title."
  (string-trim
   (replace-regexp-in-string
    "^\\*+[ \t]*\\(?:TODO\\|NEXT\\|WAIT\\|DONE\\|CANCELLED\\)[ \t]+" ""
    (replace-regexp-in-string
     "^[ \t]*-[ \t]*\\(?:\\[[ xX]\\]\\)?[ \t]*\\(?:\\[[0-9][^]]*\\]\\)?[ \t]*"
     ""
     s))))

(defun my/org-journal--day-heading-link ()
  "Return an Org bracket link to the current journal day heading."
  (let ((head (save-excursion
                (my/org-journal--goto-current-day-start)
                (buffer-substring-no-properties (point) (line-end-position)))))
    (format "[[%s][%s]]"
            (concat "file:" (expand-file-name my/org-journal-file)
                    "::" head)
            (replace-regexp-in-string "^\\*+ +" "" head))))

(defun my/org-append-promoted-task (file heading-re title link-line)
  "Insert a new TODO heading under HEADING-RE in FILE with TITLE and LINK-LINE."
  (let ((path (expand-file-name file org-directory)))
    (with-current-buffer (find-file-noselect path)
      (org-with-wide-buffer
        (goto-char (point-min))
        (unless (re-search-forward heading-re nil t)
          (user-error "Could not find heading matching %s in %s" heading-re path))
        (let ((sub-end (save-excursion
                         (goto-char (match-beginning 0))
                         (org-end-of-subtree t t)
                         (point))))
          (goto-char sub-end)
          (insert (format "\n** TODO %s\n%s\n" title link-line)))))))

(defun my/org-journal-promote-line-or-region ()
  "Promote journal line/region to a real `** TODO' heading in tasks.org.
The sorting step in the journal-first workflow — capture in journal, then
promote here with a backlink to today's entry."
  (interactive)
  (unless (and buffer-file-name
               (file-equal-p (expand-file-name buffer-file-name)
                             (expand-file-name my/org-journal-file)))
    (user-error "Promote only works in journal.org"))
  (let* ((bounds (if (use-region-p)
                     (cons (region-beginning) (region-end))
                   (cons (line-beginning-position) (line-end-position))))
         (raw (buffer-substring-no-properties (car bounds) (cdr bounds)))
         (title (my/org-journal--strip-plan-line-text
                 (if (use-region-p)
                     (replace-regexp-in-string "[\n\r]+" " " raw)
                   raw)))
         (dest "tasks.org")
         (link (concat "From journal: " (my/org-journal--day-heading-link)))
         (re "^\\* Inbox$"))
    (when (string-blank-p title)
      (user-error "Nothing to promote"))
    (my/org-append-promoted-task dest re title link)
    (save-excursion
      (my/org-journal-ensure-log-target)
      (end-of-line)
      (newline)
      (insert (format-time-string "- [%Y-%m-%d %a %H:%M] Promoted: ")
              title " → " dest))
    (message "Promoted %s to %s" title dest)))

(defun my/org-quick-task-capture ()
  "Open tasks.org (Win+T)."
  (interactive)
  (find-file (expand-file-name "tasks.org" org-directory)))

(defun my/org-journal-insert-timestamp ()
  "Append a timestamped bullet entry to today's Log section."
  (interactive)
  (my/org-journal-ensure-log-target)
  (end-of-line)
  (newline)
  (insert (format-time-string "- [%Y-%m-%d %a %H:%M] "))
  (evil-insert-state))

(defun my/org-journal-insert-task ()
  "Insert a TODO heading in today's Tasks section.
Inserts at the bottom of the section under `**** Tasks' so
new tasks always land after existing ones."
  (interactive)
  (my/org-journal-ensure-tasks-target)
  (end-of-line)
  (insert (concat "\n***** TODO "))
  (evil-insert-state))

(defvar my/eod-pending nil
  "Non-nil when today's EOD section needs attention.")

(defun my/eod-harass ()
  "Harass the user to close their EOD until they do."
  (when (>= (string-to-number (format-time-string "%H")) 18)
    (condition-case nil
        (save-window-excursion
          (find-file (expand-file-name my/org-journal-file))
          (org-datetree-find-date-create (calendar-current-date))
          (if (my/org-journal--goto-heading-in-day 4 "EOD")
              (let* ((section-start (progn (forward-line 1) (point)))
                     (section-end (my/org-journal--next-heading-point))
                     (contents (buffer-substring-no-properties section-start section-end)))
                (if (string-blank-p contents)
                    (progn
                      (setq my/eod-pending t)
                      (select-frame-set-input-focus (selected-frame))
                      (when (executable-find "powershell")
                        (call-process "powershell" nil nil nil
                          "-Command"
                          "Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.MessageBox]::Show('EOD is empty — wrap up your day!', '⚠ Journal Reminder', 'OK', 'Warning')"))
                      (ding t))
                  (setq my/eod-pending nil)))
            (setq my/eod-pending nil))
          (unless (get-buffer-window (current-buffer))
            (kill-buffer (current-buffer))))
      (error nil))))

(run-with-idle-timer 120 t #'my/eod-harass)

;; Persistent mode-line indicator — ⚠EOD shows red while EOD is empty
(push '(:eval (when my/eod-pending
                (propertize " ⚠EOD" 'face '(:background "#f38ba8" :foreground "#1e1e2e" :weight bold))))
      global-mode-string)

(defun my/org-journal-process-eod ()
  "Scan today's Tasks section and populate EOD Done/Next.
Done (closed) items are collected under ***** Done.
Still-open items are collected under ***** Next.
Original tasks in Tasks are left intact."
  (interactive)
  (save-window-excursion
    (find-file my/org-journal-file)
    (org-datetree-find-date-create (calendar-current-date))
    (my/org-journal-ensure-day-structure)
    (let (done-items open-items)
      (when (my/org-journal--goto-heading-in-day 4 "Tasks")
        (org-back-to-heading t)
        (let ((section-end (save-excursion (org-end-of-subtree t t) (point))))
          (forward-line 1)
          (while (< (point) section-end)
            (cond
             ((looking-at "^\\*\\*\\*\\*\\* DONE ")
              (push (buffer-substring-no-properties (match-end 0) (line-end-position)) done-items))
             ((looking-at "^\\*\\*\\*\\*\\* TODO ")
              (push (buffer-substring-no-properties (match-end 0) (line-end-position)) open-items))
             ((looking-at "^\\*\\*\\*\\*\\* NEXT ")
              (push (concat "NEXT " (buffer-substring-no-properties (match-end 0) (line-end-position))) open-items))
             ((looking-at "^\\*\\*\\*\\*\\* WAIT ")
              (push (concat "WAIT " (buffer-substring-no-properties (match-end 0) (line-end-position))) open-items)))
            (forward-line 1))))
      (when (or done-items open-items)
        (my/org-journal--goto-heading-in-day 4 "EOD")
        (org-back-to-heading t)
        (when done-items
          (my/org-journal--goto-heading-in-day 5 "Done"))
        (when open-items
          (my/org-journal--goto-heading-in-day 5 "Next"))
        (setq my/eod-pending nil)
        (save-buffer)
        (message "EOD processed: %d done, %d open" (length done-items) (length open-items))))))

(defun my/org-journal-fold-old-years ()
  "Fold all year-level headings before the current year when opening journal.org.
This keeps old journal entries collapsed while keeping current year expanded."
  (when (and buffer-file-name
             (file-equal-p (expand-file-name buffer-file-name)
                           (expand-file-name my/org-journal-file)))
    (let ((current-year (nth 5 (decode-time))))
      (save-excursion
        (goto-char (point-min))
        (while (re-search-forward "^\\* \\([0-9]\\{4\\}\\)" nil t)
          (let ((year (string-to-number (match-string 1))))
            (when (< year current-year)
              (ignore-errors (outline-hide-subtree)))))))))

(add-hook 'org-mode-hook #'my/org-journal-fold-old-years)
;; Journal:1 ends here

;; [[file:config.org::*Notes Frame — Kanata Integration][Notes Frame — Kanata Integration:1]]
(defvar my/home-frame nil
  "The Emacs Home frame opened by the Win+Enter launcher.")

(defun my/frame-live-p (frame)
  "Return non-nil if FRAME is a live frame, safely handling nil."
  (and frame (ignore-errors (frame-live-p frame))))

(defun my/mark-launcher-frame ()
  "Mark the current frame as the launcher frame."
  (set-frame-parameter nil 'my/launcher-frame t))

(defun my/raise-launcher-frame (frame)
  "Show FRAME, select it in Emacs, and request OS window focus."
  (when (my/frame-live-p frame)
    (make-frame-visible frame)
    (select-frame-set-input-focus frame)
    (when (fboundp 'x-focus-frame)
      (x-focus-frame frame))))

(defun my/home-frame-status ()
  "Return the home frame state: \"selected\", \"exists\", or \"no-frame\"."
  (cond ((my/frame-live-p my/home-frame)
         (if (eq my/home-frame (selected-frame)) "selected" "exists"))
        (t
         (setq my/home-frame nil)
         "no-frame")))

(defun my/home-raise ()
  "Raise and focus the home frame."
  (my/raise-launcher-frame my/home-frame))

(defun my/home-minimize ()
  "Minimize (iconify) the home frame."
  (when (my/frame-live-p my/home-frame)
    (iconify-frame my/home-frame)))

(defun my/home-frame-setup ()
  "Claim the current client frame as the Emacs Home frame.
Keeps a dedicated frame title so Komorebi can route only the Win+Enter frame
to the Emacs workspace without catching other Emacs windows."
  (setq my/home-frame (selected-frame))
  (my/mark-launcher-frame)
  (set-frame-parameter nil 'title "main - code")
  (setq default-directory (expand-file-name "~/")))

(defvar my/notes-frame nil
  "The frame opened by the Win+J journal workspace launcher.")

(defun my/notes--ensure-org-agenda-buffers ()
  "Ensure buffers in `org-agenda-files' are visiting in `org-mode'."
  (dolist (file org-agenda-files)
    (with-current-buffer (find-file-noselect file)
      (unless (derived-mode-p 'org-mode)
        (org-mode)))))

(defun my/notes-daily-review ()
  "Open the daily review: agenda on the left, today's journal on the right.
Lands in the Tasks section (legacy helper name: open-plan)."
  (interactive)
  (require 'org-agenda)
  (my/notes--ensure-org-agenda-buffers)
  (delete-other-windows)
  (setq default-directory (expand-file-name "~/"))
  (org-agenda nil "d")
  (let* ((agenda-window (selected-window))
         (plan-window   (split-window-right)))
    (with-selected-window plan-window
      (my/org-journal-open-plan))
    (when (window-live-p agenda-window) (balance-windows))
    (when (window-live-p plan-window)   (select-window plan-window))))

(defun my/notes-journal-workspace ()
  "Open today's journal (Tasks section) in a single-window notes workspace.
This is the secondary entry — switch here from daily review if you want
the full-width plan without the agenda sidebar."
  (interactive)
  (delete-other-windows)
  (setq default-directory (expand-file-name "~/"))
  (my/org-journal-open-plan))

(defun my/notes-frame-status ()
  "Return the notes frame state: \"selected\", \"exists\", or \"no-frame\"."
  (cond ((my/frame-live-p my/notes-frame)
         (if (eq my/notes-frame (selected-frame)) "selected" "exists"))
        (t
         (setq my/notes-frame nil)
         "no-frame")))

(defun my/notes-raise ()
  "Raise and focus the notes frame.
The PowerShell caller must have already called AllowSetForegroundWindow
before invoking this, otherwise Windows will silently block the focus steal."
  (my/raise-launcher-frame my/notes-frame))

(defun my/notes-minimize ()
  "Minimize (iconify) the notes frame."
  (when (my/frame-live-p my/notes-frame)
    (iconify-frame my/notes-frame)))

(defun my/notes-frame-setup ()
  "Claim the current client frame as the notes frame and open today's journal."
  (setq my/notes-frame (selected-frame))
  (my/mark-launcher-frame)
  (setq default-directory (expand-file-name "~/"))
  (my/notes-journal-workspace))
;; Notes Frame — Kanata Integration:1 ends here

;; [[file:config.org::*Notes (SPC n)][Notes (SPC n):1]]
(map! :leader
      (:prefix ("n" . "notes")
       :desc "Open today's journal"    "j" #'my/org-open-journal-today
       :desc "Daily review"            "d" #'my/notes-daily-review
       :desc "Org agenda"              "a" #'org-agenda
       :desc "Org capture"             "c" #'org-capture
       :desc "EOD process"             "e" #'my/org-journal-process-eod
       :desc "Promote to tasks.org"    "p" #'my/org-journal-promote-line-or-region
       :desc "Open tasks.org"          "t" (cmd! (find-file (expand-file-name "tasks.org" org-directory)))
       :desc "Open notes.org"          "n" (cmd! (find-file (expand-file-name "notes.org" org-directory)))
       :desc "Find/create note"        "f" #'denote-open-or-create
       :desc "Link to note"            "l" #'denote-link
       :desc "Backlinks"               "b" #'denote-backlinks
       (:prefix ("x" . "extra")
        :desc "Note graph"             "g" #'denote-explore-network
        :desc "Random note"            "w" #'denote-explore-random-note
        :desc "Isolated files"         "I" #'denote-explore-isolated-files
        :desc "Verify denote links"    "v" #'my/denote-verify-links
        :desc "Sync metadata"          "s" #'denote-explore-sync-metadata
        :desc "Rename note"            "r" #'denote-rename-file)))
;; Notes (SPC n):1 ends here

;; [[file:config.org::*Journal Keybindings][Journal Keybindings:1]]
(defun my/journal-local-bindings ()
  "Install journal-specific normal-mode bindings, scoped to journal.org."
  (when (and buffer-file-name
             (file-equal-p (expand-file-name buffer-file-name)
                           (expand-file-name my/org-journal-file)))
    (evil-local-set-key 'normal "s" #'my/org-journal-insert-timestamp)
    (evil-local-set-key 'normal "S" #'my/org-journal-insert-task)))

(add-hook 'org-mode-hook #'my/journal-local-bindings)

(defun my/denote-verify-links ()
  "Check all denote links in current file for valid IDs.
Reports broken links in a *Denote Link Check* buffer."
  (interactive)
  (let ((broken '()))
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward "\\[\\[denote:\\([0-9T]+\\)\\]" nil t)
        (let* ((id (match-string 1))
               (files (denote-directory-files id)))
          (when (null files)
            (push (format "Line %d: Broken link to %s" (line-number-at-pos) id) broken)))))
    (if broken
        (with-current-buffer (get-buffer-create "*Denote Link Check*")
          (erase-buffer)
          (insert "Broken Denote Links:\n\n")
          (dolist (b (nreverse broken)) (insert b "\n"))
          (pop-to-buffer (current-buffer)))
      (message "All Denote links valid."))))

(defun my/org-auto-clock-on-next ()
  "Auto-clock in when task state changes to NEXT."
  (when (string= org-state "NEXT")
    (org-clock-in)))

(add-hook 'org-after-todo-state-change-hook #'my/org-auto-clock-on-next)
(setq org-clock-out-when-done t)

(defun my/org-set-waiting-properties ()
  "Record WAITING_ON and WAITING_SINCE when a task is set to WAIT."
  (when (string= org-state "WAIT")
    (let ((who (read-string "Waiting on (person/service, blank to skip): ")))
      (unless (string-blank-p who)
        (org-set-property "WAITING_ON" who)))
    (org-set-property "WAITING_SINCE" (format-time-string "[%Y-%m-%d %a]"))))

(add-hook 'org-after-todo-state-change-hook #'my/org-set-waiting-properties)
;; Journal Keybindings:1 ends here

;; [[file:config.org::*Org Modern][Org Modern:1]]
(use-package! org-modern
  :hook ((org-mode            . org-modern-mode)
         (org-agenda-finalize . org-modern-agenda))
  :config
  (setq org-modern-todo-faces
        '(("TODO"      :background "#89b4fa" :foreground "#1e1e2e" :weight bold)
          ("NEXT"      :background "#a6e3a1" :foreground "#1e1e2e" :weight bold)
          ("WAIT"      :background "#f9e2af" :foreground "#1e1e2e" :weight bold)
          ("DONE"      :background "#6c7086" :foreground "#cdd6f4")
          ("CANCELLED" :background "#45475a" :foreground "#6c7086"))
        ;; Slightly thinner rules so tables feel lighter.
        org-modern-table-vertical   1
        org-modern-table-horizontal 0.2))
;; Org Modern:1 ends here

;; [[file:config.org::*Org Appear][Org Appear:1]]
(use-package! org-appear
  :hook (org-mode . org-appear-mode)
  :config
  (setq org-appear-autoemphasis   t   ; *bold* /italic/ =code= etc.
        org-appear-autolinks      t   ; [[link][desc]] — reveal brackets
        org-appear-autosubmarkers t)) ; sub/superscripts
;; Org Appear:1 ends here

;; [[file:config.org::*Org Download][Org Download:1]]
(after! org-download
  (setq org-download-method    'directory
        org-download-image-dir "./images/"         ; relative to the org file
        org-download-heading-lvl nil               ; don't include heading in filename
        org-download-timestamp "%Y%m%dT%H%M%S_")
  (map! :map org-mode-map
        :localleader
        (:prefix ("D" . "download/image")
         :desc "Paste from clipboard"  "c" #'org-download-clipboard
         :desc "Take screenshot"       "s" #'org-download-screenshot
         :desc "Yank from kill-ring"   "y" #'org-download-yank
         :desc "Delete at point"       "d" #'org-download-delete)))
;; Org Download:1 ends here

;; [[file:config.org::*Org Cliplink][Org Cliplink:1]]
(use-package! org-cliplink
  :defer t)

(map! :leader
      (:prefix ("n" . "notes")
       :desc "Insert link from clipboard (auto-title)" "L" #'org-cliplink))
;; Org Cliplink:1 ends here

;; [[file:config.org::*Org Super Agenda][Org Super Agenda:1]]
(use-package! org-super-agenda
  :after org-agenda
  :config
  (org-super-agenda-mode)
  (setq org-super-agenda-groups
        '((:name "Overdue"
           :deadline past
           :scheduled past)
          (:name "Today"
           :date today
           :time-grid t
           :scheduled today)
          (:name "Next Actions"
           :todo "NEXT")
          (:name "Waiting"
           :todo "WAIT")
          (:auto-category t)))) ; remaining items grouped by source file
;; Org Super Agenda:1 ends here

;; [[file:config.org::*Org Sticky Header][Org Sticky Header:1]]
(use-package! org-sticky-header
  :hook (org-mode . org-sticky-header-mode)
  :config
  (setq org-sticky-header-full-path            'full
        org-sticky-header-outline-path-separator " > "))
;; Org Sticky Header:1 ends here

;; [[file:config.org::*Org Transclusion][Org Transclusion:1]]
(use-package! org-transclusion
  :after org
  :config
  (map! :leader
        (:prefix ("n" . "notes")
         (:prefix ("X" . "transclusion")
          :desc "Add at point"          "a" #'org-transclusion-add
          :desc "Add all"               "A" #'org-transclusion-add-all
          :desc "Toggle mode"           "x" #'org-transclusion-mode
          :desc "Remove at point"       "r" #'org-transclusion-remove
          :desc "Refresh all"           "R" #'org-transclusion-refresh))))
;; Org Transclusion:1 ends here

;; [[file:config.org::*Org Autolist][Org Autolist:1]]
(use-package! org-autolist
  :hook (org-mode . org-autolist-mode)
  :config
  (defun my/org-smart-return (&optional default)
    "Insert next Org item; preserve checkbox continuation under Evil."
    (interactive)
    (if (and (derived-mode-p 'org-mode)
             (not (org-at-table-p))
             org-autolist-mode)
        (if (and (org-at-item-checkbox-p)
                 (not (and org-return-follows-link
                           (eq 'org-link (get-text-property (point) 'face)))))
            (progn
              (if (and (eolp)
                       (org-at-item-p)
                       (<= (point) (org-autolist-beginning-of-item-after-bullet)))
                  (condition-case nil
                      (call-interactively #'org-outdent-item)
                    (error
                     (delete-region (line-beginning-position)
                                    (line-end-position))))
                (end-of-line)
                (org-insert-todo-heading nil))
              (when (fboundp 'evil-insert-state)
                (evil-insert-state)))
          (+org/return))
      (org-return default)))

  (after! evil-org
    (evil-define-key 'normal evil-org-mode-map
      (kbd "RET") #'+org/dwim-at-point)
    (evil-define-key 'insert evil-org-mode-map
      (kbd "RET")       #'my/org-smart-return
      (kbd "<return>")  #'my/org-smart-return
      (kbd "C-m")       #'my/org-smart-return)))
;; Org Autolist:1 ends here

;; [[file:config.org::*Configuration][Configuration:1]]
(use-package! denote
  :defer t
  :init
  (setq denote-directory     (expand-file-name "notes/" org-directory)
        denote-known-keywords
        '("personal" "work" "reference" "journal" "project"
          "java" "programming" "homelab" "health" "pkm"
          "cheatsheet" "moc" "knowledge" "initiative"
           "voice" "web" "entertainment")
         denote-infer-keywords  t
        denote-sort-keywords   t
        denote-prompts         '(title keywords)
        denote-file-type       'org
        ;; Generated graph lives under notes/graph/ — not Denote notes.
        denote-excluded-directories-regexp "\\`graph[/\\\\]")
  (map! :leader
        (:prefix ("n" . "notes")
         :desc "New Denote note"          "N" #'my/denote-smart
         :desc "New note from template"   "T" #'my/denote-template-smart)))
;; Configuration:1 ends here

;; [[file:config.org::*Templates][Templates:1]]
(after! denote
  (setq denote-templates
        `((reference  . ,(concat "* Overview\n\n"
                                 "* Key Points\n\n"
                                 "* Source\n"))
          (person     . ,(concat ":PROPERTIES:\n"
                                 ":RELATIONSHIP: \n"
                                 ":BIRTHDAY:     \n"
                                 ":EMAIL:        \n"
                                 ":PHONE:        \n"
                                 ":LOCATION:     \n"
                                 ":END:\n\n"
                                 "* About\n\n"
                                 "* Notes\n\n"
                                 "* Log\n"))
          (initiative . ,(concat ":PROPERTIES:\n"
                                 ":STATUS: active\n"
                                 ":URL:    \n"
                                 ":END:\n\n"
                                 "* Goal\n\n"
                                 "* Tasks\n\n"
                                 "* Notes\n\n"
                                 "* Log\n"))
          (knowledge  . ,(concat "* Overview\n\n"
                                 "* Key Ideas\n\n"
                                 "* References\n")))))
;; Templates:1 ends here

;; [[file:config.org::*Note Types][Note Types:1]]
(defun my/denote--library-subdirectory (keywords)
  "Return absolute subdirectory under `denote-directory' for KEYWORDS.
Uses the same sorted + slugified keyword string Denote puts in filenames, then
maps a few special cases so cheatsheets stay under =personal/= and MOC under
=pkm/=."
  (unless keywords
    (user-error "Pick at least one keyword"))
  (let* ((sorted (denote-keywords-sort (copy-sequence keywords)))
         (slug-parts (denote-sluggify-keywords-and-apply-rules sorted))
         (combined (denote-keywords-combine slug-parts))
         (primary (car (split-string combined "_"))))
    (expand-file-name
     (concat
      (pcase primary
        ("cheatsheet" "personal")
        ("moc" "pkm")
        ((or "java" "tools" "personal" "pkm" "programming" "health"
             "homelab" "reference" "ai" "project" "work" "journal"
             "knowledge" "initiative" "voice" "web" "saved"
             "entertainment")
         primary)
        (_ "reference"))
      "/")
     (denote-directory))))

(defun my/denote-smart ()
  "Like `denote', but file the new note under a keyword subdirectory."
  (interactive)
  (let* ((title (denote-title-prompt))
         (keywords (denote-keywords-prompt))
         (denote-use-directory (my/denote--library-subdirectory keywords)))
    (denote title keywords 'org)))

(defun my/denote-template-smart ()
  "Like `denote-template', filing under a keyword subdirectory."
  (interactive)
  (let ((denote-prompts (denote-add-prompts '(template))))
    (let* ((title (denote-title-prompt))
           (keywords (denote-keywords-prompt))
           (denote-use-title title)
           (denote-use-keywords keywords)
           (denote-use-directory (my/denote--library-subdirectory keywords)))
      (denote))))

(defun my/denote-person ()
  "Create a person note (personal keyword, person template).
Intentionally unbound from SPC n — available via M-x as an infrequent action."
  (interactive)
  (let ((denote-use-directory (my/denote--library-subdirectory '("personal"))))
    (denote (denote-title-prompt) '("personal") 'org nil nil 'person)))

(defun my/denote-initiative ()
  "Create an initiative note (initiative keyword, initiative template)."
  (interactive)
  (let ((denote-use-directory (my/denote--library-subdirectory '("initiative"))))
    (denote (denote-title-prompt) '("initiative") 'org nil nil 'initiative)))

(defun my/denote-reference ()
  "Create a reference note (reference keyword, reference template)."
  (interactive)
  (let ((denote-use-directory (my/denote--library-subdirectory '("reference"))))
    (denote (denote-title-prompt) '("reference") 'org nil nil 'reference)))

(defun my/denote-knowledge ()
  "Create a knowledge note (knowledge keyword, knowledge template)."
  (interactive)
  (let ((denote-use-directory (my/denote--library-subdirectory '("knowledge"))))
    (denote (denote-title-prompt) '("knowledge") 'org nil nil 'knowledge)))

(defun my/denote-quick (title)
  "Create a Denote note with TITLE, prompting for keywords.
Designed for non-interactive call from emacsclient --eval
(e.g. Flow Launcher Quick Emacs plugin keyword d)."
  (let* ((keywords (denote-keywords-prompt))
         (denote-use-directory (my/denote--library-subdirectory keywords)))
    (denote title keywords 'org)))

(after! denote
  (map! :leader
        (:prefix ("n" . "notes")
         :desc "New reference note"   "r" #'my/denote-reference
         :desc "New knowledge note"   "k" #'my/denote-knowledge
         :desc "New initiative note"  "i" #'my/denote-initiative)))
;; Note Types:1 ends here

;; [[file:config.org::*Org Integration][Org Integration:1]]
(use-package! denote-org
  :after denote
  :commands
  (denote-org-link-to-heading
   denote-org-backlinks-for-heading
   denote-org-extract-org-subtree
   denote-org-convert-links-to-file-type
   denote-org-convert-links-to-denote-type
   denote-org-dblock-insert-files
   denote-org-dblock-insert-links
   denote-org-dblock-insert-backlinks
   denote-org-dblock-insert-missing-links
   denote-org-dblock-insert-files-as-headings))
;; Org Integration:1 ends here

;; [[file:config.org::*Explore][Explore:1]]
(use-package! denote-explore
  :after denote
  :init
  (setq denote-explore-network-directory (expand-file-name "graph/" denote-directory)
        denote-explore-network-filename  "denote-network"
        denote-explore-network-format    'd3.js))
;; Explore:1 ends here

;; [[file:config.org::*Windows][Windows:1]]
(map! :n "C-h" #'evil-window-left
      :n "C-j" #'evil-window-down
      :n "C-k" #'evil-window-up
      :n "C-l" #'evil-window-right
      :n "C-=" #'evil-window-increase-width
      :n "C--" #'evil-window-decrease-width
      :n "C-+" #'evil-window-increase-height
      :n "C-_" #'evil-window-decrease-height)

(map! :after evil
      :map evil-window-map
      :desc "Close window"    "x" #'evil-window-delete
      :desc "Exchange window" "e" #'evil-window-exchange)
;; Windows:1 ends here

;; [[file:config.org::*Buffers][Buffers:1]]
(map! :leader
      (:prefix ("b" . "buffer")
       :desc "Kill buffer"            "x" #'kill-current-buffer
       :desc "Open scratch buffer"    "s" #'doom/open-scratch-buffer
       :desc "Switch to scratch"      "S" #'doom/switch-to-scratch-buffer))
;; Buffers:1 ends here

;; [[file:config.org::*Tabs][Tabs:1]]
(setq tab-bar-auto-width           t
      tab-bar-auto-width-max       '((140) 14)
      tab-bar-close-button-show    nil
      tab-bar-new-button-show      nil
      tab-bar-button-margin        0
      tab-bar-tab-name-function    #'tab-bar-tab-name-truncated
      tab-bar-tab-name-truncated-max 12)

(add-hook 'doom-first-buffer-hook #'tab-bar-mode)

(map! :n "H" #'tab-bar-switch-to-prev-tab
      :n "L" #'tab-bar-switch-to-next-tab)

;; Copy Doom's SPC t (toggle) map to SPC T, then reclaim SPC t for tabs.
(dolist (leader (list (and (boundp 'doom-leader-map)     doom-leader-map)
                      (and (boundp 'doom-leader-alt-map) doom-leader-alt-map)))
  (when leader
    (let ((toggle-map (lookup-key leader (kbd "t"))))
      (when (keymapp toggle-map)
        (define-key leader (kbd "T") (copy-keymap toggle-map))
        (define-key leader (kbd "t") (make-sparse-keymap))))))

(after! which-key
  (which-key-add-key-based-replacements
    (concat doom-leader-key     " T") "Toggle"
    (concat doom-leader-alt-key " T") "Toggle"
    (concat doom-leader-key     " t") "tabs"
    (concat doom-leader-alt-key " t") "tabs"))

(map! :leader
      (:prefix ("t" . "tabs")
       :desc "New tab"          "n" #'tab-bar-new-tab
       :desc "Close tab"        "x" #'tab-bar-close-tab
       :desc "Duplicate tab"    "d" #'tab-bar-duplicate-tab
       :desc "Close other tabs" "o" #'tab-bar-close-other-tabs
       :desc "Move tab left"    "," (cmd! (tab-bar-move-tab -1))
       :desc "Move tab right"   "." (cmd! (tab-bar-move-tab 1))))
;; Tabs:1 ends here

;; [[file:config.org::*Text Scale][Text Scale:1]]
(map! :n "g+" #'text-scale-increase
      :n "g-" #'text-scale-decrease
      :n "g0" (cmd! (text-scale-set 0)))
;; Text Scale:1 ends here

;; [[file:config.org::*Toggles][Toggles:1]]
(map! :leader
      :desc "Toggle word wrap"        "T w" #'+word-wrap-mode
      :desc "Toggle undecorated frame" "T u" #'my/toggle-undecorated-frame)
;; Toggles:1 ends here

;; [[file:config.org::*File Picker][File Picker:1]]
(after! consult
  (consult-customize
   consult-fd consult-find
   my/find-file-project-first my/find-file-from-directory
   my/find-file-from-home my/find-file-from-system-root
   :state (consult--file-preview)
   :preview-key 'any))

(defun my/find-file-project-first ()
  "Fast project-first file picker using the consult backend chain."
  (interactive)
  (let ((root (or (doom-project-root) default-directory)))
    (cond
     ((fboundp 'consult-fd)   (consult-fd root))
     ((fboundp 'consult-find) (consult-find root))
     (t (call-interactively #'find-file)))))

(defun my/find-file-from-directory (dir)
  "Fuzzy-find files from DIR using the consult backend chain."
  (let ((dir (expand-file-name dir)))
    (cond
     ((fboundp 'consult-fd)   (consult-fd dir))
     ((fboundp 'consult-find) (consult-find dir))
     (t (let ((default-directory dir))
          (call-interactively #'find-file))))))

(defun my/find-file-from-home ()
  "Fuzzy-find files from HOME regardless of current project."
  (interactive)
  (my/find-file-from-directory "~/"))

(defun my/find-file-from-system-root ()
  "Fuzzy-find files from Windows filesystem root (C:/)."
  (interactive)
  (my/find-file-from-directory "C:/"))

(defun my/find-recent-file-project-first ()
  "Recent file picker via consult-recent-file."
  (interactive)
  (if (fboundp 'consult-recent-file)
      (consult-recent-file)
    (call-interactively #'recentf-open-files)))

(map! :leader
      :desc "Find file (project-first)"     "f f" #'my/find-file-project-first
      :desc "Find file from HOME"           "."   #'my/find-file-from-home
      :desc "Find file (project-first)"     "p f" #'my/find-file-project-first
      :desc "Find file from C:/"            "f x" #'my/find-file-from-system-root
      :desc "Recent files"                  "f r" #'my/find-recent-file-project-first
      :desc "Switch buffer"                "f b" #'consult-buffer
      :desc "Grep project"                 "f g" #'my/search-project-live
      :desc "Search line"                  "f l" #'consult-line
      :desc "Shell history"                "f h" #'consult-history
      :desc "Denote note"                  "f n" #'denote-open-or-create
      :desc "Org heading"                  "f o" #'consult-org-heading)
;; File Picker:1 ends here

;; [[file:config.org::*Search][Search:1]]
(defun my/search-project-live ()
  "Live grep from project root with consult-ripgrep."
  (interactive)
  (let ((root (or (doom-project-root) default-directory)))
    (if (fboundp 'consult-ripgrep)
        (consult-ripgrep root)
      (call-interactively #'rgrep))))

(defun my/search-directory-live ()
  "Live grep in the current directory with consult-ripgrep."
  (interactive)
  (if (fboundp 'consult-ripgrep)
      (consult-ripgrep default-directory)
    (call-interactively #'rgrep)))

(defun my/switch-buffer-or-file ()
  "Unified switcher: buffers, recent files, and bookmarks via consult-buffer."
  (interactive)
  (if (fboundp 'consult-buffer)
      (consult-buffer)
    (call-interactively #'switch-to-buffer)))

(map! :leader
      :desc "Search project (live)"          "s p" #'my/search-project-live
      :desc "Search project (live)"          "/"   #'my/search-project-live
      :desc "Search current directory"       "s d" #'my/search-directory-live
      :desc "Switch buffer / recent / bookmarks" "b b" #'my/switch-buffer-or-file
      :desc "Switch buffer / recent / bookmarks" ","   #'my/switch-buffer-or-file)

(after! embark
  (map! :map minibuffer-local-map
        "C-."     #'embark-act
        "C-c C-e" #'embark-export
        "C-c C-c" #'embark-collect))
;; Search:1 ends here

;; [[file:config.org::*Treemacs][Treemacs:1]]
(setq +treemacs-git-mode 'deferred)

(defun my/treemacs-enable-filewatch ()
  "Enable Treemacs file-watching, deferred until Treemacs is first used."
  (when (fboundp 'treemacs-filewatch-mode)
    (treemacs-filewatch-mode 1)))

(defun my/toggle-file-explorer ()
  "Lazy-load Treemacs, then toggle the file explorer panel."
  (interactive)
  (if (or (featurep 'treemacs) (require 'treemacs nil t))
      (progn
        (my/treemacs-enable-filewatch)
        (call-interactively #'+treemacs/toggle))
    (message "Treemacs is not available.")))

(after! treemacs
  (setq treemacs-collapse-dirs                  3
        treemacs-indentation                    1
        treemacs-indentation-string             " "
        treemacs-width                          35
        treemacs-position                       'left
        treemacs-select-when-already-in-treemacs 'stay)
  ;; evil-define-key* overrides treemacs' own tree-navigation bindings
  ;; so C-h/j/k/l always navigate to adjacent windows.
  (evil-define-key* '(normal) treemacs-mode-map
    "C-h" #'evil-window-left
    "C-j" #'evil-window-down
    "C-k" #'evil-window-up
    "C-l" #'evil-window-right))

(map! :leader
      :desc "File explorer" "e" #'my/toggle-file-explorer)
;; Treemacs:1 ends here

;; [[file:config.org::*Frames][Frames:1]]
;; Fixes tiling bounds on multi-monitor setups with different DPIs/sizes
(setq frame-resize-pixelwise t
      window-resize-pixelwise t)

(defun my/toggle-undecorated-frame ()
  "Toggle the title bar and rounded corners on the current frame."
  (interactive)
  (if (display-graphic-p)
      (let* ((current (frame-parameter nil 'undecorated))
             (new     (not current)))
        (set-frame-parameter nil 'undecorated new)
        (modify-all-frames-parameters `((undecorated . ,new)))
        (if new
            (progn
              (set-frame-parameter nil 'undecorated-round t)
              (set-frame-parameter nil 'internal-border-width 14))
          (progn
            (set-frame-parameter nil 'undecorated-round nil)
            (set-frame-parameter nil 'internal-border-width 0)))
        (message "Undecorated + Rounded Corners: %s" (if new "ON" "OFF")))
    (message "Undecorated frame toggle requires a GUI frame.")))
;; Frames:1 ends here

;; [[file:config.org::*Vertico Enhancements — preview, navigation, transient dispatch][Vertico Enhancements — preview, navigation, transient dispatch:1]]
;; ── 1. C-j/C-k in the minibuffer ──────────────────────────────────────
(map! :map vertico-map
      "C-j" #'vertico-next
      "C-k" #'vertico-prev
      "C-d" #'vertico-scroll-down
      "C-u" #'vertico-scroll-up)

;; ── 2. Live preview on cursor movement ────────────────────────────────
(after! consult
  (consult-customize
   consult-ripgrep consult-git-grep consult-line
   consult-buffer consult-recent-file consult-bookmark
   :preview-key 'any))

;; ── 3. SPC SPC transient dispatch ────────────────────────────────────
(after! transient
  (transient-define-prefix my/telescope-dispatch ()
    "Telescope-style picker dispatch."
    ["Search"
     ["File & buffer"
      ("f" "Find files"       my/find-file-project-first)
      ("b" "Switch buffer"    consult-buffer)
      ("r" "Recent files"     consult-recent-file)]
     ["Content"
      ("g" "Grep project"     my/search-project-live)
      ("l" "Search line"      consult-line)
      ("h" "Shell history"    consult-history)]
     ["Notes"
      ("n" "Denote note"      denote-open-or-create)
      ("o" "Org heading"      consult-org-heading)]
     ["Tools"
      ("i" "Imenu"            consult-imenu)
      ("c" "Complex command"  consult-complex-command)
      ("y" "Yank from kill ring" consult-yank-from-kill-ring)
      ("a" "Org agenda"       consult-org-agenda)]]
    ;; C-g / ESC cancels — same as any transient
    )

  (map! :leader
        :desc "Telescope dispatch" "SPC" #'my/telescope-dispatch))
;; Vertico Enhancements — preview, navigation, transient dispatch:1 ends here

;; [[file:config.org::*Consult-flycheck — diagnostics in consult][Consult-flycheck — diagnostics in consult:1]]
(when (and (modulep! :checkers syntax -flymake)
           (fboundp 'consult-flycheck))
  (map! :leader
        :desc "Diagnostics (flycheck)" "f e" #'consult-flycheck))
;; Consult-flycheck — diagnostics in consult:1 ends here

;; [[file:config.org::*vertico-posframe — floating child frame][vertico-posframe — floating child frame:1]]
(defun my/posframe-bottom-center-margin (info)
  "Position at bottom center with a 100px margin from the frame edge."
  (cons (/ (- (plist-get info :parent-frame-width)
              (plist-get info :posframe-width))
           2)
        (- (plist-get info :parent-frame-height)
           (plist-get info :posframe-height)
           100)))

(after! vertico-posframe
  ;; Floating panel appearance — surface0 background to distinguish from
  ;; the main frame's base, with a visible border.
  (set-face-attribute 'vertico-posframe nil
    :background "#313244" :foreground "#cdd6f4")  ; surface0 bg, text fg
  (set-face-attribute 'vertico-posframe-border nil
    :background "#585b70")                         ; surface2 border
  (setq vertico-posframe-parameters
        '((left-fringe . 8)
          (right-fringe . 8)
          (child-frame-border-width . 3)
          (internal-border-width . 10)))
  (setq vertico-posframe-border-width 3)           ; thicker border
  (setq vertico-posframe-min-height 5)
  (setq vertico-posframe-poshandler #'my/posframe-bottom-center-margin)
  (setq vertico-posframe-width 80))

;; Catppuccin-themed selection face for the highlighted candidate
(after! vertico
  (set-face-attribute 'vertico-current nil
    :background "#313244" :foreground "#cdd6f4"))
;; vertico-posframe — floating child frame:1 ends here

;; [[file:config.org::*vertico-multiform — per-command layouts][vertico-multiform — per-command layouts:1]]
(after! vertico-multiform
  ;; Grid layout for theme switching — shows candidates in a grid.
  (add-to-list 'vertico-multiform-commands
               '(consult-theme grid))
  ;; Unobtrusive for commands that return a single candidate quickly.
  (add-to-list 'vertico-multiform-commands
               '(consult-yank-from-kill-ring unobtrusive)))
;; vertico-multiform — per-command layouts:1 ends here

;; [[file:config.org::*vertico-quick — Tridactyl-style hints][vertico-quick — Tridactyl-style hints:1]]
(use-package! vertico-quick
  :after vertico
  :bind (:map vertico-map
         ("M-q" . vertico-quick-jump)))
;; vertico-quick — Tridactyl-style hints:1 ends here

;; [[file:config.org::*Web — TypeScript / JavaScript / HTML / CSS][Web — TypeScript / JavaScript / HTML / CSS:1]]
(setq-default js-indent-level 2)

;; If Projectile doesn't pick up ~/dev as a search path automatically:
;; (after! projectile
;;   (add-to-list 'projectile-project-search-path "~/dev/" :append))
;; Web — TypeScript / JavaScript / HTML / CSS:1 ends here

;; [[file:config.org::*LSP-LTeX — LanguageTool in text/org/markdown buffers][LSP-LTeX — LanguageTool in text/org/markdown buffers:1]]
(use-package! lsp-ltex
  :hook ((org-mode markdown-mode text-mode) . (lambda ()
                                          (require 'lsp-ltex)
                                          (lsp-deferred)))
  :init
  (setq lsp-ltex-version "15.2.0"))
;; LSP-LTeX — LanguageTool in text/org/markdown buffers:1 ends here

;; [[file:config.org::*AI Assistance — Copilot + Claude Code][AI Assistance — Copilot + Claude Code:1]]
(defun my/copilot-maybe-enable ()
  "Enable `copilot-mode' only in interactive, file-backed buffers."
  (when (and (not noninteractive)
             buffer-file-name
             (not (minibufferp)))
    (copilot-mode 1)))

(use-package! copilot
  :defer t
  :hook ((prog-mode        . my/copilot-maybe-enable)
         (git-commit-mode  . my/copilot-maybe-enable))
  :config
  (setq copilot-max-char  -1
        copilot-idle-delay 0.2)
  (map! :map copilot-completion-map
        :i "C-<tab>" #'copilot-accept-completion
        :i "M-]"     #'copilot-accept-completion-by-word
        :i "M-}"     #'copilot-accept-completion-by-line
        :i "M-["     #'copilot-previous-completion
        :i "M-."     #'copilot-next-completion))

(use-package! claude-code
  :defer t
  :config
  (setq claude-code-mcp-ping-interval 60))

(map! "C-c c c" #'claude-code-transient
      "C-c c p" #'copilot-mode
      "C-c c P" #'copilot-diagnose)
;; AI Assistance — Copilot + Claude Code:1 ends here

;; [[file:config.org::*System][System:1]]
(defun my/close-frame-or-kill-emacs ()
  "Close the current client frame in daemon mode; otherwise kill Emacs.
Bound to =M-F4= so the standard Windows close gesture deletes a client frame
without prompting for unsaved buffers or tearing the daemon down."
  (interactive)
  (if (and (daemonp) (frame-parameter nil 'client))
      (let ((delete-frame-functions
             (remq '+workspaces-delete-associated-workspace-h
                   delete-frame-functions))
            (server-done-hook
             (remq '+workspaces-delete-associated-workspace-h
                   server-done-hook)))
        (delete-frame))
    (save-buffers-kill-terminal)))

(map! "M-<f4>"   #'my/close-frame-or-kill-emacs
      "M-S-<f4>" #'save-buffers-kill-terminal)

(defun my/disable-workspaces-delete-associated-workspace (&rest _)
  "Override advice that prevents Doom from deleting workspaces on frame close."
  nil)

(defun my/launcher-frame-p (&optional frame)
  "Return non-nil if FRAME was marked as the launcher frame."
  (frame-parameter frame 'my/launcher-frame))

(defun my/safe-delete-frame (frame)
  "Delete FRAME without triggering Doom workspace or server cleanup.

Suppresses `delete-frame-functions' and `server-done-hook' handlers that
would delete the associated workspace or kill the Emacs client, so daemon
client frames can be closed individually without side effects."
  (let ((delete-frame-functions
         (remq 'server-handle-delete-frame
               (remq '+workspaces-delete-associated-workspace-h
                     delete-frame-functions)))
        (server-done-hook
         (remq '+workspaces-delete-associated-workspace-h
               server-done-hook)))
    (delete-frame frame t)))

(defun my/handle-delete-frame (event)
  "Handle a `delete-frame' EVENT from Emacs's special-event-map.

Daemon client frames are deleted via `my/safe-delete-frame'. All other
frames are handled by Emacs's default `handle-delete-frame'."
  (interactive "e")
  (let ((frame (posn-window (event-start event))))
    (if (and (daemonp)
             (framep frame)
             (frame-parameter frame 'client))
        (my/safe-delete-frame frame)
      (handle-delete-frame event))))

(advice-remove '+workspaces-delete-associated-workspace-h
               #'my/disable-workspaces-delete-associated-workspace)
(advice-add '+workspaces-delete-associated-workspace-h
            :override #'my/disable-workspaces-delete-associated-workspace)
(remove-hook 'delete-frame-functions #'+workspaces-delete-associated-workspace-h)
(remove-hook 'server-done-hook #'+workspaces-delete-associated-workspace-h)
(define-key special-event-map [delete-frame] #'my/handle-delete-frame)
;; System:1 ends here

;; [[file:config.org::*Startup][Startup:1]]
(defun my/emacs-home-default-directory ()
  "Set default-directory to HOME for the initial frame."
  (setq default-directory (expand-file-name "~/")))

(defun my/emacsclient-frame-default-directory (_frame)
  "Normalize default-directory for every new client frame.
Prevents inheriting wscript.exe's C:/Windows/System32 working directory
when frames are launched via Kanata's LWin+Enter binding.
If the current buffer has a file inside ~/Documents/org/ (the notes git
repo), leave default-directory at the file's directory so vc-git-root
and diff-hl resolve the notes repo, not the YADM dotfiles repo."
  (if (and buffer-file-name
           (string-prefix-p (expand-file-name "~/Documents/org/")
                            (expand-file-name buffer-file-name)))
      (setq default-directory (file-name-directory buffer-file-name))
    (setq default-directory (expand-file-name "~/"))))

(add-hook 'after-init-hook          #'my/emacs-home-default-directory)
(add-hook 'after-make-frame-functions #'my/emacsclient-frame-default-directory)

;; Force Unix (LF) line endings for .org files — Emacs on Windows defaults
;; to utf-8-dos (CRLF), which breaks git and tangling.
(add-hook 'org-mode-hook (lambda () (setq-local buffer-file-coding-system 'utf-8-unix)))

;; Qutebrowser Ctrl+E now uses emacsclientw -c (creates a new client frame)
;; with -F '((title . "qute-edit")) so komorebi floats it above the browser.
;; After saving, signal done so emacsclientw exits and qutebrowser reads the
;; result back.
(defun my/qute-temp-p ()
  "Return non-nil if the current buffer is a qutebrowser editor temp file."
  (and buffer-file-name
       (string-prefix-p (expand-file-name (or (getenv "TMPDIR") temporary-file-directory))
                        (expand-file-name buffer-file-name))
       (string-match-p "qutebrowser-editor-" buffer-file-name)))

(defun my/qute-edit-setup ()
  "Set the frame title so komorebi ignores (floats) this frame."
  (when (my/qute-temp-p)
    (set-frame-parameter nil 'title "qute-edit")))

(add-hook 'find-file-hook #'my/qute-edit-setup)

(after! evil
  (defadvice! my/qute-editor-advice (&rest _)
    :after '(evil-write evil-save-buffer)
    (when (my/qute-temp-p)
      (server-edit))))
;; Startup:1 ends here

;; [[file:config.org::*Org Protocol][Org Protocol:1]]
(require 'org-protocol)
(setq org-protocol-always-new-frame nil)

;; ── Custom protocol: journal-log (yl in Tridactyl) ──────────────────────────

(defun my/org-protocol-journal-log (data)
  "Insert a browser link into today's Log section (same as `s' but with link).
DATA is the org-protocol plist with :url, :title, and optional :note."
  (let* ((url   (or (plist-get data :url) ""))
         (title (or (plist-get data :title) url))
         (note  (or (plist-get data :note) ""))
         (ts    (format-time-string "- [%Y-%m-%d %a %H:%M] ")))
    (require 'org-datetree)
    (find-file my/org-journal-file)
    (org-datetree-find-date-create (calendar-current-date))
    (my/org-journal-ensure-day-structure)
    (my/org-journal-goto-log-section)
    (end-of-line)
    (newline)
    (insert ts "[[" url "][" title "]]")
    (unless (string-empty-p note)
      (insert " " note))
    (insert " ")
    (save-buffer)))

(add-to-list 'org-protocol-protocol-alist
  '("journal-log" :protocol "journal-log"
    :function my/org-protocol-journal-log
    :kill-client t))

;; ── Custom protocol: journal-task (yt in Tridactyl) ─────────────────────────

(defun my/org-protocol-journal-task (data)
  "Insert a browser TODO into today's Tasks section (same as `S' but with link).
DATA is the org-protocol plist with :url, :title, and optional :note."
  (let* ((url   (or (plist-get data :url) ""))
         (title (or (plist-get data :title) url))
         (note  (or (plist-get data :note) "")))
    (require 'org-datetree)
    (find-file my/org-journal-file)
    (org-datetree-find-date-create (calendar-current-date))
    (my/org-journal-ensure-day-structure)
    (my/org-journal--goto-tasks-section)
    (end-of-line)
    (insert "\n***** TODO [[" url "][" title "]]")
    (unless (string-empty-p note)
      (insert " " note))
    (insert " ")
    (save-buffer)))

(add-to-list 'org-protocol-protocol-alist
  '("journal-task" :protocol "journal-task"
    :function my/org-protocol-journal-task
    :kill-client t))

;; ── Custom protocol: journal-article (ya in Tridactyl) ──────────────────────

(defun my/org-protocol--slugify (s)
  "Convert S to a Denote-compatible file slug."
  (let ((slug (downcase (string-trim s))))
    (setq slug (replace-regexp-in-string "[^a-z0-9 ]" "" slug))
    (setq slug (replace-regexp-in-string " +" "-" slug))
    (setq slug (replace-regexp-in-string "-+" "-" slug))
    (setq slug (replace-regexp-in-string "^-\\|-$" "" slug))
    (if (string-empty-p slug) "untitled" slug)))

(defun my/org-protocol-journal-article (data)
  "Save extracted article body as a Denote reference note.
Adds a link in today's journal Log.
DATA is the org-protocol plist with :url, :title, and :body."
  (let* ((url         (or (plist-get data :url) ""))
         (title       (or (plist-get data :title) url))
         (body        (or (plist-get data :body) ""))
         (now         (current-time))
         (identifier  (format-time-string "%Y%m%dT%H%M%S" now))
         (denote-date (format-time-string "[%Y-%m-%d %a]" now))
         (journal-ts  (format-time-string "[%Y-%m-%d %a %H:%M]" now))
         (slug        (my/org-protocol--slugify title))
         (target-dir  (expand-file-name "saved"
                        (expand-file-name "notes" org-directory)))
         (fname       (format "%s/%s--%s__saved_web.org"
                               target-dir identifier slug))
         (denote-link (format "[[denote:%s][%s]]" identifier title)))
    ;; Create target directory if needed
    (make-directory target-dir t)
    ;; Write Denote note
    (with-temp-file fname
      (set-buffer-file-coding-system 'utf-8)
      (insert (format "#+title:      %s\n" title))
      (insert (format "#+date:       %s\n" denote-date))
      (insert "#+filetags:   :saved:web:\n")
      (insert (format "#+identifier: %s\n" identifier))
      (insert "\n* Source\n\n")
      (insert (format "[[%s][%s]]\n\n" url title))
      (when (org-string-nw-p body)
        (insert "* Summary\n\n")
        (insert (replace-regexp-in-string
                 "[^[:print:]\n\t]" " "
                 (string-trim body))
                "\n")))
    ;; Log in today's journal
    (require 'org-datetree)
    (find-file my/org-journal-file)
    (org-datetree-find-date-create (calendar-current-date))
    (my/org-journal-ensure-day-structure)
    (my/org-journal-goto-log-section)
    (end-of-line)
    (newline)
    (insert (format "- %s Saved article: %s\n" journal-ts denote-link))
    (save-buffer)))

(add-to-list 'org-protocol-protocol-alist
  '("journal-article" :protocol "journal-article"
    :function my/org-protocol-journal-article
    :kill-client t))

;; Legacy l/jt capture templates removed 2026-05-17.
;; Tridactyl uses journal-log/journal-task custom protocol handlers only.
;; Keeping my/org-journal-capture-log-target and -task-target functions
;; in case internal Emacs capture is needed later.

;; ── Custom protocol: denote-link (yd in Tridactyl/qutebrowser) ─────────────

(defun my/org-protocol-denote-link (data)
  "Create a Denote reference note from a browser URL and TITLE.
DATA is the org-protocol plist with :url and :title.
This is a pure Denote capture — no journal entry is created."
  (let* ((url        (or (plist-get data :url) ""))
         (title      (or (plist-get data :title) url))
         (keywords   '("reference" "web"))
         (dir        (my/denote--library-subdirectory keywords))
         (id         (format-time-string "%Y%m%dT%H%M%S"))
         (slug       (denote-sluggify title))
         (kw-combined (denote-keywords-combine
                       (denote-sluggify-keywords-and-apply-rules keywords)))
         (fname      (format "%s/%s--%s__%s.org" dir id slug kw-combined)))
    (make-directory dir t)
    (with-temp-file fname
      (set-buffer-file-coding-system 'utf-8)
      (insert (format "#+title:      %s\n" title))
      (insert (format "#+date:       %s\n" (format-time-string "[%Y-%m-%d %a]")))
      (insert "#+filetags:   :reference:web:\n")
      (insert (format "#+identifier: %s\n\n" id))
      (insert "* Source\n\n")
      (insert (format "[[%s][%s]]\n\n" url title))
      (insert "* Key Points\n\n")
      (insert "* Overview\n\n"))
    (message "Denote: saved %s as reference note" title)))

(add-to-list 'org-protocol-protocol-alist
  '("denote-link" :protocol "denote-link"
    :function my/org-protocol-denote-link
    :kill-client t))
;; Org Protocol:1 ends here

;; [[file:config.org::*Org Buffer Checking][Org Buffer Checking:1]]
(after! flycheck
  (add-hook 'org-mode-hook
            (lambda ()
              (setq-local flycheck-disabled-checkers
                          (cons 'org-lint flycheck-disabled-checkers)))))
;; Org Buffer Checking:1 ends here

;; [[file:config.org::*Auto-Tangle Literate Configs][Auto-Tangle Literate Configs:1]]
(defun my/auto-tangle-config-org ()
  "Tangle the current buffer if it's a .org file in ~/.config/.
Shows a message when tangling completes."
  (when (and buffer-file-name
             (string-match-p "/\\.config/.*\\.org\\'" buffer-file-name))
    (let ((start-time (current-time)))
      (org-babel-tangle)
      (message "Tangled %s (%.1fs)"
               (file-name-nondirectory buffer-file-name)
               (float-time (time-subtract (current-time) start-time))))))

(add-hook 'after-save-hook #'my/auto-tangle-config-org)
;; Auto-Tangle Literate Configs:1 ends here
