;; [[file:config.org::*Bootstrapper =early-init.el=][Bootstrapper =early-init.el=:1]]
;;; $DOOMDIR/early-init.el -*- lexical-binding: t; -*-

;; =============================================================
;; DO NOT EDIT THIS FILE DIRECTLY.
;; Generated from ~/.config/doom/config.org
;; Edit that file, tangle with `tangle config`,
;; then restart Emacs.
;; =============================================================

;; Change the process CWD before Emacs creates internal buffers,
;; so they inherit ~/ instead of c:/Windows/TEMP/ (fixes diff-hl).
(cd "~/")
;; Bootstrapper =early-init.el=:1 ends here
