;;; init.el -*- lexical-binding: t; -*-
;; Doom module declarations.
;; Edit init.org instead — this file is generated by `tangle init`.
;; After changes: doom sync + restart Emacs.

(doom!

 ;; ── Completion ────────────────────────────────────────────────────────────────
 ;; In-buffer completion and interactive narrowing/selection.
 :completion
 (corfu +orderless)  ; Corfu for in-buffer completions; orderless for fuzzy
                     ; space-separated matching across any completing-read UI
 (vertico +childframe +icons)  ; Vertico + posframe child-frame UI + file icons

 ;; ── User Interface ────────────────────────────────────────────────────────────
 ;; Visual chrome, themes, and structural UI modules.
 :ui
 (doom +icons)       ; Doom's icon support via nerd-icons (replaces all-the-icons)
 dashboard           ; Startup splash dashboard with recent files / agenda
 hl-todo             ; Highlight TODO/FIXME/HACK/NOTE keywords in source
 (modeline +light)   ; Doom modeline; +light skips heavy git state computation
 ophints             ; Flash operator targets (yank, delete, etc.) in Evil
 (popup +defaults)   ; Intelligent popup window management with sane defaults
 (vc-gutter +pretty) ; Git gutter signs in the fringe; +pretty uses nerd-icons
 vi-tilde-fringe     ; Show ~ in fringe for lines beyond end of buffer (Vim feel)
 workspaces          ; Named workspace tabs via perspective.el
 (treemacs +icons)   ; Sidebar file-tree; +icons enables nerd-icons decorations

 ;; ── Editor ────────────────────────────────────────────────────────────────────
 ;; Text editing enhancements layered on top of Evil.
 :editor
 (evil +everywhere)  ; Vim modal editing in every buffer (not just prog-mode)
 file-templates      ; Snippet-based default content for new files (yasnippet)
 fold                ; Code folding via hideshow / ts-fold
 format              ; Auto-format on save via apheleia (uses per-lang formatters)
 multiple-cursors    ; Multi-cursor editing via evil-multiedit / evil-mc
 snippets            ; Yasnippet with Doom's built-in snippet library
 (whitespace +guess  ; Highlight trailing/mixed whitespace;
             +trim)  ; +guess infers indent style; +trim strips on save
 word-wrap           ; Soft word-wrap with =M-x +word-wrap-mode=

 ;; ── Core Emacs ────────────────────────────────────────────────────────────────
 ;; Doom wrappers around built-in Emacs subsystems.
 :emacs
 dired               ; Enhanced dired with Evil bindings and icons
 electric            ; Auto-close pairs (parens, brackets, quotes)
 tramp               ; Remote file editing via SSH / sudo (tramp.el)
 undo                ; Persistent undo history via undo-fu + undo-fu-session
 vc                  ; Version-control integration (magit supplements this)

 ;; ── Terminal ──────────────────────────────────────────────────────────────────
 :term
 vterm               ; Fast terminal emulator using libvterm (C library)
                      ; Requires libvterm shared library (winget install GnuWin32.Make then M-x vterm-compile)

 ;; ── Checkers ──────────────────────────────────────────────────────────────────
 :checkers
 (syntax -flymake)    ; On-the-fly syntax checking via flycheck (instead of flymake)
                      ; -flymake flag means: use flycheck, not the built-in flymake

 ;; ── Tools ─────────────────────────────────────────────────────────────────────
 ;; Integrations with external tools and services.
 :tools
 (eval +overlay)     ; Inline code evaluation; +overlay shows results in-buffer
 lookup              ; Go-to-definition, documentation, online search (xref)
 lsp                 ; Language Server Protocol client via lsp-mode
 magit               ; Full-featured Git interface
 tree-sitter         ; Structural syntax trees for smarter highlighting/editing
                     ; Requires Emacs 29.1+ — grammars pulled for :lang js + web

 ;; ── OS Integration ────────────────────────────────────────────────────────────
 :os
 (:if (featurep :system 'macos) macos)  ; macOS-specific tweaks (no-op on Windows)

 ;; ── Languages ─────────────────────────────────────────────────────────────────
 ;; Per-language modules. Each installs a major mode, LSP config, and
 ;; optional tree-sitter grammar.  +lsp wires the language into lsp-mode.
 ;; +tree-sitter enables structural editing and better highlighting.
 :lang
 emacs-lisp          ; Emacs Lisp — elisp-mode, eros eval, helpful
 (javascript +lsp    ; JS/TS/TSX via typescript-ts-mode + LSP (ts-ls / eslint)
             +tree-sitter)
 (org +dragndrop)    ; Org Mode with drag-and-drop image attachment support
 markdown            ; Markdown preview via grip or pandoc
 json                ; json-mode + lsp-mode for JSON editing
 yaml                ; yaml-mode for YAML/TOML-adjacent files
 (python +lsp)       ; Python via python-mode + pyright/pylsp
 (rust +lsp)         ; Rust via rust-mode + rust-analyzer
 (web +lsp           ; HTML, CSS, JSX templates via web-mode + LSP
      +tree-sitter)  ; Pairs with javascript module for Vite/React stack
 sh                  ; Bash/sh/zsh via sh-mode

 ;; ── Configuration Layer ───────────────────────────────────────────────────────
 ;; Doom's own sensible defaults layer.  Always keep this last.
 :config
 (default +bindings  ; Doom's default keybindings (SPC leader, g/z prefixes)
          +smartparens))  ; Smartparens for structural pair management
