;;; packages.el -*- lexical-binding: t; -*-
;; Third-party packages not covered by Doom modules.
;; Edit init.org instead — this file is generated by `tangle init`.
;; After changes: doom sync (straight.el fetches new packages automatically).

;; Catppuccin Mocha — matches the system-wide color palette used in
;; Windows Terminal, Flow Launcher, Starship, and PSReadLine.
(package! catppuccin-theme)

;; Extra nerd-icons pack specifically for Treemacs sidebar decorations.
;; Supplements the base +icons flag set in the (treemacs +icons) module.
(package! treemacs-all-the-icons)

(package! denote)          ; Core: create, rename, link notes by ID
(package! denote-explore)  ; Visualise note graph and orphans
(package! denote-org)      ; Org-specific: org-capture templates, org-insert-link

(package! org-autolist)       ; Auto-continue list items on RET
(package! org-modern)         ; Clean, modern Org appearance (stars → bullets, etc.)
(package! org-appear)         ; Reveal markup (bold, links) on cursor entry
(package! org-cliplink)       ; Paste a URL and auto-fetch its title as a link
(package! org-super-agenda)   ; Group agenda items by custom selectors
(package! org-sticky-header)  ; Pin the current section header to the top line
(package! org-transclusion)   ; Inline-embed content from other org files

;; Convert Markdown to Org. Used during the obs2org migration workflow.
;; Source: https://github.com/modeverv/markdown-to-org
(package! markdown-to-org
  :recipe (:host github :repo "modeverv/markdown-to-org"))

;; GitHub Copilot inline completions.
;; Source: https://github.com/copilot-emacs/copilot.el
(package! copilot
  :recipe (:host github :repo "copilot-emacs/copilot.el" :files ("*.el")))

;; Claude Code integration — run Claude Code sessions inside Emacs buffers.
;; Source: https://github.com/yuya373/claude-code-emacs
(package! claude-code
  :recipe (:host github :repo "yuya373/claude-code-emacs"))

(package! lsp-ltex)

(package! minimap)
