-- =============================================================================
-- DO NOT EDIT THIS FILE DIRECTLY.
-- Generated from ~/.config/wezterm/wezterm.org
-- =============================================================================

local wezterm = require 'wezterm'
local config = wezterm.config_builder()

config.font = wezterm.font 'CaskaydiaCove NFM'
config.font_size = 12.0
config.color_scheme = 'Catppuccin Mocha'

-- Fully opaque background. Transparency effects disabled.
config.window_background_opacity = 1.0

-- Steady block cursor, no blink (erratic blink is distracting).
config.default_cursor_style = 'SteadyBlock'
config.cursor_blink_rate = 0

config.window_decorations = "RESIZE"
config.enable_tab_bar = true
config.hide_tab_bar_if_only_one_tab = true
config.use_fancy_tab_bar = false
config.tab_max_width = 32
config.default_prog = { 'pwsh.exe', '-NoLogo' }

local act = wezterm.action

config.keys = {
  -- Tabs
  { key = 't', mods = 'CTRL', action = act.SpawnTab 'CurrentPaneDomain' },
  { key = 'h', mods = 'CTRL', action = act.ActivateTabRelative(-1) },
  { key = 'l', mods = 'CTRL', action = act.ActivateTabRelative(1) },
  { key = ',', mods = 'CTRL', action = act.MoveTabRelative(-1) },
  { key = 'h', mods = 'CTRL|SHIFT', action = act.ActivatePaneDirection 'Left' },
  { key = '.', mods = 'CTRL', action = act.MoveTabRelative(1) },
  { key = 'l', mods = 'CTRL|SHIFT', action = act.ActivatePaneDirection 'Right' },
  { key = 'j', mods = 'CTRL|SHIFT', action = act.ActivatePaneDirection 'Down' },
  { key = 'k', mods = 'CTRL|SHIFT', action = act.ActivatePaneDirection 'Up' },

  -- Panes
  { key = '\\', mods = 'CTRL', action = act.SplitHorizontal { domain = 'CurrentPaneDomain' } },
  { key = '-', mods = 'CTRL', action = act.SplitVertical { domain = 'CurrentPaneDomain' } },
  { key = 'q', mods = 'CTRL', action = act.CloseCurrentPane { confirm = false } },
  { key = 'd', mods = 'CTRL|SHIFT', action = act.SplitHorizontal { domain = 'CurrentPaneDomain' } },

  -- Pane Focus
  { key = 'h', mods = 'CTRL|ALT', action = act.ActivatePaneDirection 'Left' },
  { key = 'j', mods = 'CTRL|ALT', action = act.ActivatePaneDirection 'Down' },
  { key = 'k', mods = 'CTRL|ALT', action = act.ActivatePaneDirection 'Up' },
  { key = 'l', mods = 'CTRL|ALT', action = act.ActivatePaneDirection 'Right' },

  -- Tab renaming
  {
    key = 'r',
    mods = 'CTRL',
    action = act.PromptInputLine {
      description = 'Enter new name for tab',
      action = wezterm.action_callback(function(window, pane, line)
        if line then
          window:active_tab():set_title(line)
        end
      end),
    },
  },

  -- Custom Escape + Enter
  { key = 'Enter', mods = 'SHIFT', action = act.SendString '\x1b\r' },
}

-- Tab numbers (Ctrl+1 to Ctrl+9, and Ctrl+0 for 10)
for i = 1, 9 do
  table.insert(config.keys, {
    key = tostring(i),
    mods = 'CTRL',
    action = act.ActivateTab(i - 1),
  })
end
table.insert(config.keys, { key = '0', mods = 'CTRL', action = act.ActivateTab(9) })

-- Clipboard: Ctrl+C copy, Ctrl+Shift+C SIGINT (cancel)
table.insert(config.keys, { key = 'c', mods = 'CTRL', action = act.CopyTo 'Clipboard' })
table.insert(config.keys, { key = 'c', mods = 'CTRL|SHIFT', action = act.SendKey { key = 'C', mods = 'CTRL' } })
table.insert(config.keys, { key = 'v', mods = 'CTRL|SHIFT', action = act.PasteFrom 'Clipboard' })

return config
